# Generated by Django 2.0.5 on 2018-08-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_auto_20180805_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='image',
            field=models.ImageField(upload_to='display/static/display/uploads/'),
        ),
    ]
